### ISSUE TITLE
Placing raw kettle crashes the game.

### ISSUE THREAD

**Issue by Shadeloid** [jayugg/BalancedThirst#1]
When i was placing the raw kettle in the pit kiln, the game crashed. 
Version: 1.19.8

[server-main.txt](https://github.com/user-attachments/files/15945087/server-main.txt)
[client-main.txt](https://github.com/user-attachments/files/15945088/client-main.txt)

**Comment by jacopouggeri** [comment]
Did you just place a raw kettle, then add grass? Because when I try to do it nothing happens. The method that crashes is also very simple, I'll add some extra null checks but I can't do much else without seeing it in action.

**Comment by SpearAndFang** [comment]
"System.NullReferenceException: Object reference not set to an instance of an object.
   at BalancedThirst.HarmonyPatches.CollObj.CollectibleObject_**tryEatBegin**_Patch.Postfix"
   
   maybe they accidently tried to drink from the raw kettle?

**Comment by Shadeloid** [comment]
No, i just placed the kettle on the grass to make a pit, but the moment i used ctrl+ right click to place it, it crashed imedietly.

**Comment by jacopouggeri** [comment]
Does it still crash with the new version? I got 3 reports of this but I was never able to replicate it. I added some extra null checks in the patch that might solve the issue, although the null exception was at the end of the patch because, correctly, you cannot drink a raw kettle, so the method should return immediately.

**Comment by Shadeloid** [comment]
It's fixed now. I didn't crash anymore.
